### ISSUE TITLE
Authorization via openstreetmap.org fails

### ISSUE THREAD

**Issue by patricks** [OsmoTagger/OsmoTagger#9]
Currently I am not able login via OAuth 2.0. I always get the following error: ![image](https://github.com/OsmoTagger/OsmoTagger/assets/132167/d08e3069-aee3-4841-9f37-93dbd248cdae)

![image](https://github.com/OsmoTagger/OsmoTagger/assets/132167/b404eb82-a232-4fb9-a993-e5b90879e776)

**Comment by molind** [comment]
Fixed in 1.1
